---
openapi: 3.0.1
info:
  description: API for Users Management
  version: v1
  title: Users
host: localhost
basePath: /v1
tags:
- name: user
  description: Operations about user
schemes:
- https
- http
paths:
  /users:
    get:
      tags:
      - user
      summary: Get all users
      description: Returns a json with all users (optionally sorted and ordered, default - sorted by salary descending)
      operationId: getUsers
      produces:
      - application/json
      parameters:
      - name: sort_by
        in: query
        description: sort method (by id, first name, last name, salary)
        required: false
        type: string
        enum:
        - id
        - fname
        - lname
        - ysalary
      - name: order
        in: query
        description: order method (ascending, descending)
        required: false
        type: string
        enum:
        - ASC
        - DESC
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      tags:
      - user
      summary: Add user
      operationId: addUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: userId
        description: User object to be added
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "201":
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        "409":
          description: ID already exists
        "405":
          description: Invalid input
  /users/{userId}:
    get:
      tags:
      - user
      summary: Find user by ID
      description: Returns a single user
      operationId: getUserById
      produces:
      - application/json
      parameters:
      - name: userId
        in: path
        description: ID of user to return
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
    patch:
      tags:
      - user
      summary: Add user
      operationId: patchUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: userId
        in: path
        description: User object to be added
        required: true
        type: integer
        format: int64
      - in: body
        name: user
        description: User object to be added
        required: true
        schema:
          $ref: '#/definitions/user'
      responses:
        "201":
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        "409":
          description: ID already exists
        "405":
          description: Invalid input
definitions:
  User:
    type: object
    required:
    - fname
    - id
    - lname
    - ysalary
    properties:
      id:
        type: integer
      fname:
        type: string
      lname:
        type: string
      ysalary:
        type: integer
  usersuserId_user:
    type: object
    required:
    - fname
    - lname
    - ysalary
    properties:
      fname:
        type: string
      lname:
        type: string
      ysalary:
        type: integer
  user:
    type: object
    required:
    - user
    properties:
      user:
        $ref: '#/definitions/usersuserId_user'
